//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelsorterApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixelsorterApp.Resources.Languages.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an image, choose options, and sort..
        /// </summary>
        internal static string AppSlogan {
            get {
                return ResourceManager.GetString("AppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base preset set as default..
        /// </summary>
        internal static string BasePresetSetAsDefault {
            get {
                return ResourceManager.GetString("BasePresetSetAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keeps edges unsorted.
        /// </summary>
        internal static string CannyView_details {
            get {
                return ResourceManager.GetString("CannyView_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity threshold.
        /// </summary>
        internal static string CannyView_Threshold {
            get {
                return ResourceManager.GetString("CannyView_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canny edge mask.
        /// </summary>
        internal static string CannyView_Title {
            get {
                return ResourceManager.GetString("CannyView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string common_Accept {
            get {
                return ResourceManager.GetString("common_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string common_Cancel {
            get {
                return ResourceManager.GetString("common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string common_Delete {
            get {
                return ResourceManager.GetString("common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        internal static string common_Dismiss {
            get {
                return ResourceManager.GetString("common_Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load RAW Images (dng files).
        /// </summary>
        internal static string common_dngErrorMessage {
            get {
                return ResourceManager.GetString("common_dngErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        internal static string common_DontAccept {
            get {
                return ResourceManager.GetString("common_DontAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string common_Edit {
            get {
                return ResourceManager.GetString("common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string common_Error {
            get {
                return ResourceManager.GetString("common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string common_NA {
            get {
                return ResourceManager.GetString("common_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string common_None {
            get {
                return ResourceManager.GetString("common_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string common_OK {
            get {
                return ResourceManager.GetString("common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string common_Save {
            get {
                return ResourceManager.GetString("common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string common_Unknown {
            get {
                return ResourceManager.GetString("common_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing luminance....
        /// </summary>
        internal static string CycleSortingMessagesAnalyzingLuminance {
            get {
                return ResourceManager.GetString("CycleSortingMessagesAnalyzingLuminance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying subject mask....
        /// </summary>
        internal static string CycleSortingMessagesApplyingSubjectMask {
            get {
                return ResourceManager.GetString("CycleSortingMessagesApplyingSubjectMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arranging pixels {0}....
        /// </summary>
        internal static string CycleSortingMessagesArrangingPixels {
            get {
                return ResourceManager.GetString("CycleSortingMessagesArrangingPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining masks....
        /// </summary>
        internal static string CycleSortingMessagesCombiningMasks {
            get {
                return ResourceManager.GetString("CycleSortingMessagesCombiningMasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting edges....
        /// </summary>
        internal static string CycleSortingMessagesDetectingEdges {
            get {
                return ResourceManager.GetString("CycleSortingMessagesDetectingEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading pixel data....
        /// </summary>
        internal static string CycleSortingMessagesReadingPixelData {
            get {
                return ResourceManager.GetString("CycleSortingMessagesReadingPixelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting by {0}....
        /// </summary>
        internal static string CycleSortingMessagesSortingBy {
            get {
                return ResourceManager.GetString("CycleSortingMessagesSortingBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted preset &apos;{0}&apos;..
        /// </summary>
        internal static string DeletedPresetPresetName {
            get {
                return ResourceManager.GetString("DeletedPresetPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The masking model could not be downloaded. Please check your internet connection and try again..
        /// </summary>
        internal static string DownloadFailed_Message {
            get {
                return ResourceManager.GetString("DownloadFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        internal static string DownloadFailed_Title {
            get {
                return ResourceManager.GetString("DownloadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading AI model....
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading preset &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorLoadingPresetPresetNameExMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingPresetPresetNameExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving preset: {0}.
        /// </summary>
        internal static string ErrorSavingPreset {
            get {
                return ResourceManager.GetString("ErrorSavingPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECTION.
        /// </summary>
        internal static string ExampleGallery_BeforeAfterView_DIRECTION {
            get {
                return ResourceManager.GetString("ExampleGallery_BeforeAfterView_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS USED.
        /// </summary>
        internal static string ExampleGallery_BeforeAfterView_SETTINGSUSED {
            get {
                return ResourceManager.GetString("ExampleGallery_BeforeAfterView_SETTINGSUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORT BY.
        /// </summary>
        internal static string ExampleGallery_BeforeAfterView_SORTBY {
            get {
                return ResourceManager.GetString("ExampleGallery_BeforeAfterView_SORTBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the slider to compare the original and sorted image..
        /// </summary>
        internal static string ExampleGallery_DragTheSliderToCompareTheOriginalAndSortedImage {
            get {
                return ResourceManager.GetString("ExampleGallery_DragTheSliderToCompareTheOriginalAndSortedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASKING OPTIONS.
        /// </summary>
        internal static string HeaderMaskingOptions {
            get {
                return ResourceManager.GetString("HeaderMaskingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORT SETTINGS.
        /// </summary>
        internal static string HeaderSortSettings {
            get {
                return ResourceManager.GetString("HeaderSortSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixelsorter loads an image, sorts its pixels in a chosen direction using a chosen colour criterion, and lets you preview and save results.
        ///
        ///The main screen is organised like this:
        ///
        ///- **Image preview** (tap to load an image)
        ///- **Sort settings** (what to sort by + sorting direction)
        ///- **Masking options** (optional: limit which pixels are allowed to move)
        ///- **Sort** button (creates a new sorted result)
        ///- **Save** button (saves the currently displayed result)
        ///
        ///---
        ///
        ///
        ///## Loading an image
        ///
        ///### Load  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpPage_Content {
            get {
                return ResourceManager.GetString("HelpPage_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use the Pixelsorter.
        /// </summary>
        internal static string HelpPage_DisplayPageName_HowToUseThePixelsorter {
            get {
                return ResourceManager.GetString("HelpPage_DisplayPageName_HowToUseThePixelsorter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid preset name..
        /// </summary>
        internal static string InvalidPresetName {
            get {
                return ResourceManager.GetString("InvalidPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages are sorted by their native names..
        /// </summary>
        internal static string LanguagesAreSortedByTheirNativeNames {
            get {
                return ResourceManager.GetString("LanguagesAreSortedByTheirNativeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string LanguageSettingsView_ChooseLanguage {
            get {
                return ResourceManager.GetString("LanguageSettingsView_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language settings.
        /// </summary>
        internal static string LanguageSettingsView_LanguageSettings {
            get {
                return ResourceManager.GetString("LanguageSettingsView_LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the app after changing the language for the best experience..
        /// </summary>
        internal static string LanguageSettingsView_Restart {
            get {
                return ResourceManager.GetString("LanguageSettingsView_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can only guarantee that the German and English versions are always fully translated. For other languages, some content may be missing, in which case it will be replaced by the English terms..
        /// </summary>
        internal static string LanguageSettingsView_TranslationGuarantee {
            get {
                return ResourceManager.GetString("LanguageSettingsView_TranslationGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by {0}.
        /// </summary>
        internal static string LicensePage_ByItemAuthors {
            get {
                return ResourceManager.GetString("LicensePage_ByItemAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence information unavailable.
        /// </summary>
        internal static string LicensePage_LicenseInformationUnavailable {
            get {
                return ResourceManager.GetString("LicensePage_LicenseInformationUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses the following open source packages:.
        /// </summary>
        internal static string LicensesPage_Explenation {
            get {
                return ResourceManager.GetString("LicensesPage_Explenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded preset &apos;{0}&apos;..
        /// </summary>
        internal static string LoadedPresetPresetName {
            get {
                return ResourceManager.GetString("LoadedPresetPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mask based on image luminance.
        /// </summary>
        internal static string LuminanceMaskView_Details {
            get {
                return ResourceManager.GetString("LuminanceMaskView_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        internal static string LuminanceMaskView_Threshold {
            get {
                return ResourceManager.GetString("LuminanceMaskView_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminance mask.
        /// </summary>
        internal static string LuminanceMaskView_Title {
            get {
                return ResourceManager.GetString("LuminanceMaskView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverted.
        /// </summary>
        internal static string LuminanceMaskView_WhatToSort_Inverted {
            get {
                return ResourceManager.GetString("LuminanceMaskView_WhatToSort_Inverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string LuminanceMaskView_WhatToSort_Normal {
            get {
                return ResourceManager.GetString("LuminanceMaskView_WhatToSort_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The masking feature uses a pre-trained machine learning model that was created by a third party. By enabling this feature, you accept that you won&apos;t use pictures created or edited by this tool for any commercial purposes. For further information, go to the licence page..
        /// </summary>
        internal static string MaskingFeatureLicense_Message {
            get {
                return ResourceManager.GetString("MaskingFeatureLicense_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masking feature licence.
        /// </summary>
        internal static string MaskingFeatureLicense_Title {
            get {
                return ResourceManager.GetString("MaskingFeatureLicense_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string MaskOptionsView_WhatToSort_Title {
            get {
                return ResourceManager.GetString("MaskOptionsView_WhatToSort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Info.
        /// </summary>
        internal static string Navigation_Title {
            get {
                return ResourceManager.GetString("Navigation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new preset.
        /// </summary>
        internal static string NewPresetAction {
            get {
                return ResourceManager.GetString("NewPresetAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internet connection is required to use the masking feature. Please connect to the internet and try again..
        /// </summary>
        internal static string NoInternetConnection_Message {
            get {
                return ResourceManager.GetString("NoInternetConnection_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string NoInternetConnection_Title {
            get {
                return ResourceManager.GetString("NoInternetConnection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original image.
        /// </summary>
        internal static string OriginalImage {
            get {
                return ResourceManager.GetString("OriginalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example gallery.
        /// </summary>
        internal static string PageName_ExampleGallery {
            get {
                return ResourceManager.GetString("PageName_ExampleGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string PageName_HelpPage {
            get {
                return ResourceManager.GetString("PageName_HelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source Licences.
        /// </summary>
        internal static string PageName_OpenSourceLicenses {
            get {
                return ResourceManager.GetString("PageName_OpenSourceLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets page.
        /// </summary>
        internal static string PageName_PresetsPage {
            get {
                return ResourceManager.GetString("PageName_PresetsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PageName_PrivacyPolicy {
            get {
                return ResourceManager.GetString("PageName_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PageName_Settings {
            get {
                return ResourceManager.GetString("PageName_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixelsorter.
        /// </summary>
        internal static string PixelSorterHeader {
            get {
                return ResourceManager.GetString("PixelSorterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset saved successfully..
        /// </summary>
        internal static string PresetSavedSuccessfully {
            get {
                return ResourceManager.GetString("PresetSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVAILABLE PRESETS.
        /// </summary>
        internal static string PresetsPage_AvilablePresets_Header {
            get {
                return ResourceManager.GetString("PresetsPage_AvilablePresets_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your preset by configuring the options below. The currently shown preset is based on your selections. Use the TOML map to find out how to configure each option..
        /// </summary>
        internal static string PresetsPage_CreateYourPresetExplenation {
            get {
                return ResourceManager.GetString("PresetsPage_CreateYourPresetExplenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESET DETAILS.
        /// </summary>
        internal static string PresetsPage_Header {
            get {
                return ResourceManager.GetString("PresetsPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset name.
        /// </summary>
        internal static string PresetsPage_NewPresetName_Title {
            get {
                return ResourceManager.GetString("PresetsPage_NewPresetName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        internal static string PresetsPage_Preset {
            get {
                return ResourceManager.GetString("PresetsPage_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset TOML.
        /// </summary>
        internal static string PresetsPage_PresetEditor_Heading {
            get {
                return ResourceManager.GetString("PresetsPage_PresetEditor_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save preset.
        /// </summary>
        internal static string PresetsPage_SavePreset {
            get {
                return ResourceManager.GetString("PresetsPage_SavePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default preset.
        /// </summary>
        internal static string PresetsPage_SetAsDefaultPreset {
            get {
                return ResourceManager.GetString("PresetsPage_SetAsDefaultPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set base preset as default.
        /// </summary>
        internal static string PresetsPage_SetBasePresetAsDefault {
            get {
                return ResourceManager.GetString("PresetsPage_SetBasePresetAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset {0}.
        /// </summary>
        internal static string PresetsPageViewModel_PresetsPageViewModel_NewPresetName {
            get {
                return ResourceManager.GetString("PresetsPageViewModel_PresetsPageViewModel_NewPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESETS.
        /// </summary>
        internal static string PresetsView_Header {
            get {
                return ResourceManager.GetString("PresetsView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        internal static string PresetsView_Presets {
            get {
                return ResourceManager.GetString("PresetsView_Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save image.
        /// </summary>
        internal static string SaveAsync_FailedToSaveImage {
            get {
                return ResourceManager.GetString("SaveAsync_FailedToSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image saved.
        /// </summary>
        internal static string SaveAsync_ImageSaved {
            get {
                return ResourceManager.GetString("SaveAsync_ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image available to save..
        /// </summary>
        internal static string SaveAsync_NoImageAvailableToSave {
            get {
                return ResourceManager.GetString("SaveAsync_NoImageAvailableToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image available to share..
        /// </summary>
        internal static string ShareAsync_NoImageAvailableToShare {
            get {
                return ResourceManager.GetString("ShareAsync_NoImageAvailableToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share failed: {0}.
        /// </summary>
        internal static string ShareAsync_ShareFailed {
            get {
                return ResourceManager.GetString("ShareAsync_ShareFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a look at this pixel-sorted image I created with {0}.
        /// </summary>
        internal static string ShareFeature_AdTextWithPlatformLink {
            get {
                return ResourceManager.GetString("ShareFeature_AdTextWithPlatformLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share sorted image.
        /// </summary>
        internal static string ShareFeature_ShareDialog_Title {
            get {
                return ResourceManager.GetString("ShareFeature_ShareDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        internal static string SortAsync_AnErrorOccurredExMessage {
            get {
                return ResourceManager.GetString("SortAsync_AnErrorOccurredExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by: {0} • Direction: {1}.
        /// </summary>
        internal static string SortCaption {
            get {
                return ResourceManager.GetString("SortCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chroma.
        /// </summary>
        internal static string SortStrings_by_chroma {
            get {
                return ResourceManager.GetString("SortStrings_by_chroma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coolness.
        /// </summary>
        internal static string SortStrings_by_cool {
            get {
                return ResourceManager.GetString("SortStrings_by_cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        internal static string SortStrings_by_hue {
            get {
                return ResourceManager.GetString("SortStrings_by_hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightness.
        /// </summary>
        internal static string SortStrings_by_light {
            get {
                return ResourceManager.GetString("SortStrings_by_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrancy.
        /// </summary>
        internal static string SortStrings_by_perVib {
            get {
                return ResourceManager.GetString("SortStrings_by_perVib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        internal static string SortStrings_by_sat {
            get {
                return ResourceManager.GetString("SortStrings_by_sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warmth.
        /// </summary>
        internal static string SortStrings_by_warm {
            get {
                return ResourceManager.GetString("SortStrings_by_warm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Bottom to Top.
        /// </summary>
        internal static string SortStrings_direction_cbt {
            get {
                return ResourceManager.GetString("SortStrings_direction_cbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Top to Bottom.
        /// </summary>
        internal static string SortStrings_direction_ctb {
            get {
                return ResourceManager.GetString("SortStrings_direction_ctb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Into mask.
        /// </summary>
        internal static string SortStrings_direction_im {
            get {
                return ResourceManager.GetString("SortStrings_direction_im", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Left to Right.
        /// </summary>
        internal static string SortStrings_direction_rlr {
            get {
                return ResourceManager.GetString("SortStrings_direction_rlr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Right to Left.
        /// </summary>
        internal static string SortStrings_direction_rrl {
            get {
                return ResourceManager.GetString("SortStrings_direction_rrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect people or objects, sort around them.
        /// </summary>
        internal static string SubjectMaskOptionsView_Details {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string SubjectMaskOptionsView_HowToCombineMasks_Add {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_HowToCombineMasks_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canny and subject masks are combined when both masking options are enabled. The Canny mask is used as the second summand or as the subtrahend for the subject mask.
        /// </summary>
        internal static string SubjectMaskOptionsView_HowToCombineMasks_explenation {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_HowToCombineMasks_explenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract.
        /// </summary>
        internal static string SubjectMaskOptionsView_HowToCombineMasks_Subtract {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_HowToCombineMasks_Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string SubjectMaskOptionsView_Padding {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject mask.
        /// </summary>
        internal static string SubjectMaskOptionsView_Title {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string SubjectMaskOptionsView_WhatToSort_Background {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_WhatToSort_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        internal static string SubjectMaskOptionsView_WhatToSort_Foreground {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_WhatToSort_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to load an image.
        /// </summary>
        internal static string TapToLoadAnImage {
            get {
                return ResourceManager.GetString("TapToLoadAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide TOML map.
        /// </summary>
        internal static string ToggleTomlMap_Hide {
            get {
                return ResourceManager.GetString("ToggleTomlMap_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show TOML map.
        /// </summary>
        internal static string ToggleTomlMap_Show {
            get {
                return ResourceManager.GetString("ToggleTomlMap_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject masking cannot be enabled because the background model is not downloaded..
        /// </summary>
        internal static string TomlValidation_BackgroundModelIsNotDownloaded {
            get {
                return ResourceManager.GetString("TomlValidation_BackgroundModelIsNotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canny_options.threshold must be in range (0, 100)..
        /// </summary>
        internal static string TomlValidation_CannyOutOfRange {
            get {
                return ResourceManager.GetString("TomlValidation_CannyOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOML content is empty..
        /// </summary>
        internal static string TomlValidation_Empty {
            get {
                return ResourceManager.GetString("TomlValidation_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load toml map..
        /// </summary>
        internal static string TomlValidation_FailedToLoadTomlMap {
            get {
                return ResourceManager.GetString("TomlValidation_FailedToLoadTomlMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOML is invalid..
        /// </summary>
        internal static string TOMLValidation_Invalid {
            get {
                return ResourceManager.GetString("TOMLValidation_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOML is invalid: {0}.
        /// </summary>
        internal static string TOMLValidation_InvalidError {
            get {
                return ResourceManager.GetString("TOMLValidation_InvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TOML syntax..
        /// </summary>
        internal static string TomlValidation_InvalidSyntax {
            get {
                return ResourceManager.GetString("TomlValidation_InvalidSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TOML syntax: {0}.
        /// </summary>
        internal static string TomlValidation_InvalidSyntaxError {
            get {
                return ResourceManager.GetString("TomlValidation_InvalidSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for {0}: &apos;{1}&apos;..
        /// </summary>
        internal static string TomlValidation_InvalidValueForFieldNameValue {
            get {
                return ResourceManager.GetString("TomlValidation_InvalidValueForFieldNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction &apos;im&apos; (Into Mask) requires at least one mask to be enabled..
        /// </summary>
        internal static string TomlValidation_MaskMustBeEnabled {
            get {
                return ResourceManager.GetString("TomlValidation_MaskMustBeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid boolean value: {0}..
        /// </summary>
        internal static string TomlValidation_MissingOrInvalidBooleanValue {
            get {
                return ResourceManager.GetString("TomlValidation_MissingOrInvalidBooleanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid integer value: {0}..
        /// </summary>
        internal static string TomlValidation_MissingOrInvalidIntegerValue {
            get {
                return ResourceManager.GetString("TomlValidation_MissingOrInvalidIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid string value: {0}..
        /// </summary>
        internal static string TomlValidation_MissingOrInvalidStringValueKey {
            get {
                return ResourceManager.GetString("TomlValidation_MissingOrInvalidStringValueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid table: [{0}]..
        /// </summary>
        internal static string TomlValidation_MissingOrInvalidTableTableName {
            get {
                return ResourceManager.GetString("TomlValidation_MissingOrInvalidTableTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject masking cannot be enabled before accepting the masking licence..
        /// </summary>
        internal static string TomlValidation_subjectLicenseNotAccepted {
            get {
                return ResourceManager.GetString("TomlValidation_subjectLicenseNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject_settings.padding must be in range [1, 100]..
        /// </summary>
        internal static string TomlValidation_SubjectPaddingOutOfRange {
            get {
                return ResourceManager.GetString("TomlValidation_SubjectPaddingOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOML is valid..
        /// </summary>
        internal static string TOMLValidation_Valid {
            get {
                return ResourceManager.GetString("TOMLValidation_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to gallery.
        /// </summary>
        internal static string WelcomeAction {
            get {
                return ResourceManager.GetString("WelcomeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a look at the example gallery to see what you can do before getting started. You can always find the gallery via the info menu..
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Pixelsorter!.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
