//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelsorterApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainPageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainPageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixelsorterApp.Resources.Languages.MainPageStrings", typeof(MainPageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an image, choose options, and sort..
        /// </summary>
        internal static string AppSlogan {
            get {
                return ResourceManager.GetString("AppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keeps edges unsorted.
        /// </summary>
        internal static string CannyView_details {
            get {
                return ResourceManager.GetString("CannyView_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity threshold.
        /// </summary>
        internal static string CannyView_Threshold {
            get {
                return ResourceManager.GetString("CannyView_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canny Edge mask.
        /// </summary>
        internal static string CannyView_Title {
            get {
                return ResourceManager.GetString("CannyView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying subject mask....
        /// </summary>
        internal static string CycleSortingMessagesApplyingSubjectMask {
            get {
                return ResourceManager.GetString("CycleSortingMessagesApplyingSubjectMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arranging pixels {0}....
        /// </summary>
        internal static string CycleSortingMessagesArrangingPixels {
            get {
                return ResourceManager.GetString("CycleSortingMessagesArrangingPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining masks....
        /// </summary>
        internal static string CycleSortingMessagesCombiningMasks {
            get {
                return ResourceManager.GetString("CycleSortingMessagesCombiningMasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting edges....
        /// </summary>
        internal static string CycleSortingMessagesDetectingEdges {
            get {
                return ResourceManager.GetString("CycleSortingMessagesDetectingEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading pixel data....
        /// </summary>
        internal static string CycleSortingMessagesReadingPixelData {
            get {
                return ResourceManager.GetString("CycleSortingMessagesReadingPixelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting by {0}....
        /// </summary>
        internal static string CycleSortingMessagesSortingBy {
            get {
                return ResourceManager.GetString("CycleSortingMessagesSortingBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The masking model could not be downloaded. Please check your internet connection and try again..
        /// </summary>
        internal static string DownloadFailed_Message {
            get {
                return ResourceManager.GetString("DownloadFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        internal static string DownloadFailed_Title {
            get {
                return ResourceManager.GetString("DownloadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASKING OPTIONS.
        /// </summary>
        internal static string HeaderMaskingOptions {
            get {
                return ResourceManager.GetString("HeaderMaskingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORT SETTINGS.
        /// </summary>
        internal static string HeaderSortSettings {
            get {
                return ResourceManager.GetString("HeaderSortSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The masking feature uses a pre-trained machine learning model that was created by a third party. By enabling this feature, you accept that you won&apos;t use pictures created or edited by this tool for any commercial purposes. For further information, go to the license page..
        /// </summary>
        internal static string MaskingFeatureLicense_Message {
            get {
                return ResourceManager.GetString("MaskingFeatureLicense_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masking Feature License.
        /// </summary>
        internal static string MaskingFeatureLicense_Title {
            get {
                return ResourceManager.GetString("MaskingFeatureLicense_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internet connection is required to use the masking feature. Please connect to the internet and try again..
        /// </summary>
        internal static string NoInternetConnection_Message {
            get {
                return ResourceManager.GetString("NoInternetConnection_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection.
        /// </summary>
        internal static string NoInternetConnection_Title {
            get {
                return ResourceManager.GetString("NoInternetConnection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original image.
        /// </summary>
        internal static string OriginalImage {
            get {
                return ResourceManager.GetString("OriginalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Sorter.
        /// </summary>
        internal static string PixelSorterHeader {
            get {
                return ResourceManager.GetString("PixelSorterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESETS.
        /// </summary>
        internal static string PresetsView_Header {
            get {
                return ResourceManager.GetString("PresetsView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        internal static string PresetsView_Presets {
            get {
                return ResourceManager.GetString("PresetsView_Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save image.
        /// </summary>
        internal static string SaveAsync_FailedToSaveImage {
            get {
                return ResourceManager.GetString("SaveAsync_FailedToSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image saved.
        /// </summary>
        internal static string SaveAsync_ImageSaved {
            get {
                return ResourceManager.GetString("SaveAsync_ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image available to save..
        /// </summary>
        internal static string SaveAsync_NoImageAvailableToSave {
            get {
                return ResourceManager.GetString("SaveAsync_NoImageAvailableToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image available to share..
        /// </summary>
        internal static string ShareAsync_NoImageAvailableToShare {
            get {
                return ResourceManager.GetString("ShareAsync_NoImageAvailableToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share failed: {0}.
        /// </summary>
        internal static string ShareAsync_ShareFailed {
            get {
                return ResourceManager.GetString("ShareAsync_ShareFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        internal static string SortAsync_AnErrorOccurredExMessage {
            get {
                return ResourceManager.GetString("SortAsync_AnErrorOccurredExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by: {0} • Direction: {1}.
        /// </summary>
        internal static string SortCaption {
            get {
                return ResourceManager.GetString("SortCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect people or objects, sort around them.
        /// </summary>
        internal static string SubjectMaskOptionsView_Details {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string SubjectMaskOptionsView_HowToCombineMasks_Add {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_HowToCombineMasks_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canny and subject masks are combined when both masking options are on. The canny mask is used as second summand or as subtrahend for the subject mask.
        /// </summary>
        internal static string SubjectMaskOptionsView_HowToCombineMasks_explenation {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_HowToCombineMasks_explenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract.
        /// </summary>
        internal static string SubjectMaskOptionsView_HowToCombineMasks_Subtract {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_HowToCombineMasks_Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to combine masks.
        /// </summary>
        internal static string SubjectMaskOptionsView_HowToCombineMasks_Title {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_HowToCombineMasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string SubjectMaskOptionsView_Padding {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject mask.
        /// </summary>
        internal static string SubjectMaskOptionsView_Title {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string SubjectMaskOptionsView_WhatToSort_Background {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_WhatToSort_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        internal static string SubjectMaskOptionsView_WhatToSort_Foreground {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_WhatToSort_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to sort
        ///.
        /// </summary>
        internal static string SubjectMaskOptionsView_WhatToSort_Title {
            get {
                return ResourceManager.GetString("SubjectMaskOptionsView_WhatToSort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to load an image.
        /// </summary>
        internal static string TapToLoadAnImage {
            get {
                return ResourceManager.GetString("TapToLoadAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Gallery.
        /// </summary>
        internal static string WelcomeAction {
            get {
                return ResourceManager.GetString("WelcomeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out the example gallery to see what you can do before getting started. You can always find the gallery via the info menu.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Pixel Sorter!.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
