//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelsorterApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PresetStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PresetStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixelsorterApp.Resources.Languages.PresetStrings", typeof(PresetStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base preset set as default..
        /// </summary>
        internal static string BasePresetSetAsDefault {
            get {
                return ResourceManager.GetString("BasePresetSetAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted preset &apos;{0}&apos;..
        /// </summary>
        internal static string DeletedPresetPresetName {
            get {
                return ResourceManager.GetString("DeletedPresetPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading preset &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorLoadingPresetPresetNameExMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingPresetPresetNameExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving preset: {0}.
        /// </summary>
        internal static string ErrorSavingPreset {
            get {
                return ResourceManager.GetString("ErrorSavingPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid preset name..
        /// </summary>
        internal static string InvalidPresetName {
            get {
                return ResourceManager.GetString("InvalidPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded preset &apos;{0}&apos;..
        /// </summary>
        internal static string LoadedPresetPresetName {
            get {
                return ResourceManager.GetString("LoadedPresetPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new preset.
        /// </summary>
        internal static string NewPresetAction {
            get {
                return ResourceManager.GetString("NewPresetAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset saved successfully..
        /// </summary>
        internal static string PresetSavedSuccessfully {
            get {
                return ResourceManager.GetString("PresetSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVAILABLE PRESETS.
        /// </summary>
        internal static string PresetsPage_AvilablePresets_Header {
            get {
                return ResourceManager.GetString("PresetsPage_AvilablePresets_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your preset by configuring the options below. The currently shown preset is based on your selections. Use the TOML map to find out how to configure each option..
        /// </summary>
        internal static string PresetsPage_CreateYourPresetExplenation {
            get {
                return ResourceManager.GetString("PresetsPage_CreateYourPresetExplenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESET DETAILS.
        /// </summary>
        internal static string PresetsPage_Header {
            get {
                return ResourceManager.GetString("PresetsPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset name.
        /// </summary>
        internal static string PresetsPage_NewPresetName_Title {
            get {
                return ResourceManager.GetString("PresetsPage_NewPresetName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        internal static string PresetsPage_Preset {
            get {
                return ResourceManager.GetString("PresetsPage_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset TOML.
        /// </summary>
        internal static string PresetsPage_PresetEditor_Heading {
            get {
                return ResourceManager.GetString("PresetsPage_PresetEditor_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save preset.
        /// </summary>
        internal static string PresetsPage_SavePreset {
            get {
                return ResourceManager.GetString("PresetsPage_SavePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default preset.
        /// </summary>
        internal static string PresetsPage_SetAsDefaultPreset {
            get {
                return ResourceManager.GetString("PresetsPage_SetAsDefaultPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set base preset as default.
        /// </summary>
        internal static string PresetsPage_SetBasePresetAsDefault {
            get {
                return ResourceManager.GetString("PresetsPage_SetBasePresetAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide TOML map.
        /// </summary>
        internal static string ToggleTomlMap_Hide {
            get {
                return ResourceManager.GetString("ToggleTomlMap_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show TOML map.
        /// </summary>
        internal static string ToggleTomlMap_Show {
            get {
                return ResourceManager.GetString("ToggleTomlMap_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject masking cannot be enabled because the background model is not downloaded..
        /// </summary>
        internal static string TomlValidation_BackgroundModelIsNotDownloaded {
            get {
                return ResourceManager.GetString("TomlValidation_BackgroundModelIsNotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canny_options.threshold must be in range (0, 100)..
        /// </summary>
        internal static string TomlValidation_CannyOutOfRange {
            get {
                return ResourceManager.GetString("TomlValidation_CannyOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOML content is empty..
        /// </summary>
        internal static string TomlValidation_Empty {
            get {
                return ResourceManager.GetString("TomlValidation_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load toml map..
        /// </summary>
        internal static string TomlValidation_FailedToLoadTomlMap {
            get {
                return ResourceManager.GetString("TomlValidation_FailedToLoadTomlMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOML is invalid..
        /// </summary>
        internal static string TOMLValidation_Invalid {
            get {
                return ResourceManager.GetString("TOMLValidation_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOML is invalid: {0}.
        /// </summary>
        internal static string TOMLValidation_InvalidError {
            get {
                return ResourceManager.GetString("TOMLValidation_InvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TOML syntax..
        /// </summary>
        internal static string TomlValidation_InvalidSyntax {
            get {
                return ResourceManager.GetString("TomlValidation_InvalidSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TOML syntax: {0}.
        /// </summary>
        internal static string TomlValidation_InvalidSyntaxError {
            get {
                return ResourceManager.GetString("TomlValidation_InvalidSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for {0}: &apos;{1}&apos;..
        /// </summary>
        internal static string TomlValidation_InvalidValueForFieldNameValue {
            get {
                return ResourceManager.GetString("TomlValidation_InvalidValueForFieldNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction &apos;im&apos; (Into Mask) requires at least one mask to be enabled..
        /// </summary>
        internal static string TomlValidation_MaskMustBeEnabled {
            get {
                return ResourceManager.GetString("TomlValidation_MaskMustBeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid boolean value: {0}..
        /// </summary>
        internal static string TomlValidation_MissingOrInvalidBooleanValue {
            get {
                return ResourceManager.GetString("TomlValidation_MissingOrInvalidBooleanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid integer value: {0}..
        /// </summary>
        internal static string TomlValidation_MissingOrInvalidIntegerValue {
            get {
                return ResourceManager.GetString("TomlValidation_MissingOrInvalidIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid string value: {0}..
        /// </summary>
        internal static string TomlValidation_MissingOrInvalidStringValueKey {
            get {
                return ResourceManager.GetString("TomlValidation_MissingOrInvalidStringValueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid table: [{0}]..
        /// </summary>
        internal static string TomlValidation_MissingOrInvalidTableTableName {
            get {
                return ResourceManager.GetString("TomlValidation_MissingOrInvalidTableTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject masking cannot be enabled before accepting the masking license..
        /// </summary>
        internal static string TomlValidation_subjectLicenseNotAccepted {
            get {
                return ResourceManager.GetString("TomlValidation_subjectLicenseNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject_settings.padding must be in range [1, 100]..
        /// </summary>
        internal static string TomlValidation_SubjectPaddingOutOfRange {
            get {
                return ResourceManager.GetString("TomlValidation_SubjectPaddingOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOML is valid..
        /// </summary>
        internal static string TOMLValidation_Valid {
            get {
                return ResourceManager.GetString("TOMLValidation_Valid", resourceCulture);
            }
        }
    }
}
