//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelsorterApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrivacyPolicyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivacyPolicyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixelsorterApp.Resources.Languages.PrivacyPolicyStrings", typeof(PrivacyPolicyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pixelsorter App generally runs fully offline. All image processing (pixel sorting, masking, etc.) takes place exclusively on your local device. No images, usage data, or other personal data are transmitted to us or to third parties..
        /// </summary>
        internal static string PrivacyPolicyPage__Part_1_1 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage__Part_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicyPage_Header {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generally offline.
        /// </summary>
        internal static string PrivacyPolicyPage_Part_1_GenerallyOffline {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_1_GenerallyOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A machine learning model is required for the automatic subject detection feature (subject masking). This model is downloaded once and only after explicit user interaction from the Hugging Face platform..
        /// </summary>
        internal static string PrivacyPolicyPage_Part_2_1 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When downloading the model, a network connection to Hugging Face servers is established. During this process, the following data may be transmitted to Hugging Face:.
        /// </summary>
        internal static string PrivacyPolicyPage_Part_2_2 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Your IP address&amp;#10;• System information (user agent of the requesting client)&amp;#10;• Time of the download.
        /// </summary>
        internal static string PrivacyPolicyPage_Part_2_3 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data processing is carried out on the basis of your consent (Art. 6(1)(a) GDPR), because the download is only triggered after your active interaction. You can revoke this consent for the future at any time by deleting the downloaded model in the app settings or by fully uninstalling the app from your device. Further information can be found in Hugging Face&apos;s privacy policy..
        /// </summary>
        internal static string PrivacyPolicyPage_Part_2_4 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the one-time download, the model is stored locally in your device&apos;s file system. No further network connections to Hugging Face or other services are made afterwards..
        /// </summary>
        internal static string PrivacyPolicyPage_Part_2_5 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Time Model download from Hugging Face.
        /// </summary>
        internal static string PrivacyPolicyPage_Part_2_HuggingFace {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_2_HuggingFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you download the app through third-party platforms (e.g., Apple App Store, Google Play Store, Microsoft Store), these providers independently collect data (e.g., download statistics or crash reports). We have no influence over this data processing. The privacy policies of the respective store operators apply..
        /// </summary>
        internal static string PrivacyPolicyPage_Part_3_1 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution via App Stores.
        /// </summary>
        internal static string PrivacyPolicyPage_Part_3_DistributionViaAppStores {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_3_DistributionViaAppStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app contains no analytics tools, no tracking, and no advertising. No usage data is collected or shared with third parties..
        /// </summary>
        internal static string PrivacyPolicyPage_Part_4_1 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Analytics or Tracking.
        /// </summary>
        internal static string PrivacyPolicyPage_Part_4_NoAnalyticsOrTracking {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_4_NoAnalyticsOrTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the right at any time to:.
        /// </summary>
        internal static string PrivacyPolicyPage_Part_5_1 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Access your personal data stored by us (Art. 15 GDPR)&amp;#10;• Rectification of inaccurate data (Art. 16 GDPR)&amp;#10;• Erasure of your data stored by us (Art. 17 GDPR)&amp;#10;• Restriction of processing (Art. 18 GDPR)&amp;#10;• Objection to processing (Art. 21 GDPR)&amp;#10;• Data portability (Art. 20 GDPR)&amp;#10;• Lodge a complaint: You have the right to lodge a complaint with a data protection supervisory authority (Art. 77 GDPR)..
        /// </summary>
        internal static string PrivacyPolicyPage_Part_5_2 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rights.
        /// </summary>
        internal static string PrivacyPolicyPage_Part_5_YourRights {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_5_YourRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This privacy policy is currently valid and reflects the status as of March 2026. As the app evolves or due to changes in legal or regulatory requirements, it may become necessary to update this privacy policy..
        /// </summary>
        internal static string PrivacyPolicyPage_Part_6_1 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Validity and Changes to This Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicyPage_Part_6_CurrentValidityAndChangesToThisPrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicyPage_Part_6_CurrentValidityAndChangesToThisPrivacyPolicy", resourceCulture);
            }
        }
    }
}
