//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelsorterApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SortStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SortStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixelsorterApp.Resources.Languages.SortStrings", typeof(SortStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chroma.
        /// </summary>
        internal static string SortStrings_by_chroma {
            get {
                return ResourceManager.GetString("SortStrings_by_chroma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coolness.
        /// </summary>
        internal static string SortStrings_by_cool {
            get {
                return ResourceManager.GetString("SortStrings_by_cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        internal static string SortStrings_by_hue {
            get {
                return ResourceManager.GetString("SortStrings_by_hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightness.
        /// </summary>
        internal static string SortStrings_by_light {
            get {
                return ResourceManager.GetString("SortStrings_by_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrancy.
        /// </summary>
        internal static string SortStrings_by_perVib {
            get {
                return ResourceManager.GetString("SortStrings_by_perVib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        internal static string SortStrings_by_sat {
            get {
                return ResourceManager.GetString("SortStrings_by_sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warmth.
        /// </summary>
        internal static string SortStrings_by_warm {
            get {
                return ResourceManager.GetString("SortStrings_by_warm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Bottom to Top.
        /// </summary>
        internal static string SortStrings_direction_cbt {
            get {
                return ResourceManager.GetString("SortStrings_direction_cbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Top to Bottom.
        /// </summary>
        internal static string SortStrings_direction_ctb {
            get {
                return ResourceManager.GetString("SortStrings_direction_ctb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Into mask.
        /// </summary>
        internal static string SortStrings_direction_im {
            get {
                return ResourceManager.GetString("SortStrings_direction_im", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Left to Right.
        /// </summary>
        internal static string SortStrings_direction_rlr {
            get {
                return ResourceManager.GetString("SortStrings_direction_rlr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Right to Left.
        /// </summary>
        internal static string SortStrings_direction_rrl {
            get {
                return ResourceManager.GetString("SortStrings_direction_rrl", resourceCulture);
            }
        }
    }
}
